import { lazy } from 'react';

import {
  DownloadOutlined,
  UserOutlined,
  UserDeleteOutlined,
  FileImageOutlined,
  PictureOutlined,
  BankOutlined,
  ChromeOutlined,
  QqOutlined,
  SettingOutlined,
  AppstoreOutlined,
} from '@ant-design/icons';

import { ROLE } from './role';
import ROUTE from '~/src/constant/routes';

const ViewWebCard = lazy(
  () => import('../ui/modules/web-card/containers/ViewListCard')
);

const CreateUpdateWebCard = lazy(
  () => import('../ui/modules/web-card/containers/CreateUpdateCard')
);

const ViewWebArticle = lazy(
  () => import('../ui/modules/web-article/containers/ViewWebArticle')
);

const ViewBanner = lazy(
  () => import('../ui/modules/mobile-banner/containers/ViewListBanner')
);

const CreateUpdateBanner = lazy(
  () => import('../ui/modules/mobile-banner/containers/CreateUpdateBanner')
);


const CreateWebArticle = lazy(
  () => import('../ui/modules/web-article/containers/CreateWebArticle')
);

const UpdateWebArticle = lazy(
  () => import('../ui/modules/web-article/containers/CreateWebArticle')
);

const ViewWebCategory = lazy(
  () => import('../ui/modules/web-category/containers/ViewWebCategory')
);

const CreateWebCategory = lazy(
  () => import('../ui/modules/web-category/containers/CreateWebCategory')
);

const UpdateWebCategory = lazy(
  () => import('../ui/modules/web-category/containers/CreateWebCategory')
);


const Login = lazy(() => import('../ui/modules/login/containers/Login'));

export const MAIN_ROUTES = [
  {
    path: '/login',
    name: 'login',
    element: Login,
  },
  {
    path: '/problem/detail-problem',
    name: 'webCards',
    element: ViewWebCard,
  },
  // {
  //   path: `${ROUTE.CARD.CREATE}`,
  //   name: 'webCardCreate',
  //   element: CreateUpdateWebCard,
  // },
  // {
  //   path: `${ROUTE.CARD.UPDATE}/:id`,
  //   name: 'webCardUpdate',
  //   element: CreateUpdateWebCard,
  // },
  {
    path: '/problems/list',
    name: 'webArticles',
    element: ViewWebArticle,
  },
  {
    path: '/problem/create',
    name: 'createWebArticle',
    element: CreateWebArticle,
  },
  {
    path: '/problem/update',
    name: 'updateWebArticle',
    element: UpdateWebArticle,
  },
  // {
  //   path: '/web-category/list',
  //   name: 'webCategories',
  //   element: ViewWebCategory,
  // },
  // {
  //   path: '/web-category/create',
  //   name: 'createWebCategory',
  //   element: CreateWebCategory,
  // },
  // {
  //   path: '/web-category/update',
  //   name: 'updateWebCategory',
  //   element: UpdateWebCategory,
  // },
  // {
  //   path: ROUTE.BANNER.LIST,
  //   name: 'banners',
  //   element: ViewBanner,
  // },
  // {
  //   path: `${ROUTE.BANNER.CREATE}`,
  //   name: 'bannerCreate',
  //   element: CreateUpdateBanner,
  // },
  // {
  //   path: `${ROUTE.BANNER.UPDATE}/:id/:type`,
  //   name: 'bannerUpdate',
  //   element: CreateUpdateBanner,
  // },
  {
    path: '',
    name: 'webCards',
    element: ViewWebCard,
  },
];

export const mobileMenus = [
  // {
  //   id: "bank",
  //   name: "Ngân hàng",
  //   icon: DownloadOutlined,
  //   route: "/banks/list",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "partner",
  //   name: "Đối tác",
  //   icon: DownloadOutlined,
  //   route: "/partners/list",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "campaign",
  //   name: "Chiến dịch",
  //   icon: DownloadOutlined,
  //   route: "/campaigns/list",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: 'product',
  //   name: 'Products',
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: 'product-card',
  //   name: 'Card',
  //   icon: DownloadOutlined,
  //   route: '/cards/list',
  //   menuParentId: 'product',
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "product-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/loans/list",
  //   menuParentId: "product",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "product-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/insurances/list",
  //   menuParentId: "product",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "product-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/securities",
  //   menuParentId: "product",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-product",
  //   name: "Active Products",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/active-products-cards/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/active-products-loans/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/active-products-insurances/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/active-products-securities/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "official-account",
  //   name: "Official Accounts",
  //   icon: DownloadOutlined,
  //   route: "/official-accounts/list",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead",
  //   name: "Lead",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/leads/card/new",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/leads/list",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead-verify",
  //   name: "Verify Lead",
  //   icon: DownloadOutlined,
  //   route: "/filter/leads",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  {
    id: 'article-parent',
    name: 'Articles',
    icon: DownloadOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'article',
    name: 'Articles',
    icon: DownloadOutlined,
    route: '/oa-articles/list',
    menuParentId: 'article-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'consent-parent',
    name: 'Consents',
    icon: UserOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'withdraw-request',
    name: 'Withdrawals',
    icon: UserDeleteOutlined,
    route: `${ROUTE.CONSENT.WITHDRAW_REQUEST_LIST}`,
    menuParentId: 'consent-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'report',
    name: 'Report',
    icon: DownloadOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  },
  // {
  //   id: "report-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/report/cards",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/report/loans",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  {
    id: 'report-insurance',
    name: 'Insurance',
    icon: DownloadOutlined,
    route: '/report/insurance',
    menuParentId: 'report',
    role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  },
  {
    id: 'report-ekyc',
    name: 'EKYC',
    icon: DownloadOutlined,
    route: '/report/ekyc',
    menuParentId: 'report',
    role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  },
  // {
  //   id: "report-loan-refill",
  //   name: "Loan Refill",
  //   icon: DownloadOutlined,
  //   route: "/report/loan-refill",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-feedback",
  //   name: "Feedback",
  //   icon: DownloadOutlined,
  //   route: "/report/feedback",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-ec-lead-status",
  //   name: "EC Lead Status",
  //   icon: DownloadOutlined,
  //   route: "/report/upload-ec-status",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/report/securities",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "message",
  //   name: "Tin nhắn",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-list",
  //   name: "Tin nhắn",
  //   icon: DownloadOutlined,
  //   route: "/messages/list",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-create",
  //   name: "Soạn tin nhắn",
  //   icon: DownloadOutlined,
  //   route: "/messages/new",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-send",
  //   name: "Gửi tin nhắn",
  //   icon: DownloadOutlined,
  //   route: "/messages/send",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-history",
  //   name: "Lịch sử",
  //   icon: DownloadOutlined,
  //   route: "/message-tracks-details-summary/list",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "broadcast",
  //   name: "Broadcast",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "broadcast-list",
  //   name: "Broadcast",
  //   icon: DownloadOutlined,
  //   route: "/broadcast/list",
  //   menuParentId: "broadcast",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "broadcast-create",
  //   name: "Tạo broadcast",
  //   icon: DownloadOutlined,
  //   route: "/broadcast/new",
  //   menuParentId: "broadcast",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "comment-approval",
  //   name: "Duyệt bình luận",
  //   icon: DownloadOutlined,
  //   route: "/review/list",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  {
    id: 'banner-parent',
    name: 'Banners',
    icon: FileImageOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'banner',
    name: 'Banners',
    icon: FileImageOutlined,
    route: `${ROUTE.BANNER.LIST}`,
    menuParentId: 'banner-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'logos-parent',
    name: 'Logos',
    icon: PictureOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'partnerLogos',
    name: 'Partner Logos',
    icon: BankOutlined,
    route: `${ROUTE.PARTNER_LOGO.LIST}`,
    menuParentId: 'logos-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'products-parent',
    name: 'Products',
    icon: ChromeOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'hotProducts',
    name: 'Hot Products',
    icon: QqOutlined,
    route: `${ROUTE.HOT_PRODUCT.LIST}`,
    menuParentId: 'products-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'promoteProducts',
    name: 'Promote Products',
    icon: QqOutlined,
    route: `${ROUTE.PROMOTE_PRODUCT.LIST}`,
    menuParentId: 'products-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'configs-parent',
    name: 'Configs',
    icon: SettingOutlined,
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  {
    id: 'configFeatures',
    name: 'Config features',
    icon: AppstoreOutlined,
    route: `${ROUTE.CONFIG_FEATURE.LIST}`,
    menuParentId: 'configs-parent',
    role: [ROLE.Admin, ROLE.OP, ROLE.Registered, ROLE.Setup, ROLE.CustomSetup],
  },
  // {
  //   id: "banner-visible",
  //   name: "Banner visible",
  //   icon: DownloadOutlined,
  //   route: "/banner/visible",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-welcome",
  //   name: "Welcome banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/welcome",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-featured",
  //   name: "Featured banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/featured",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-masthead",
  //   name: "Masthead banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/masthead",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-loanform",
  //   name: "Loanform banner step 1",
  //   icon: DownloadOutlined,
  //   route: "/banner/loanform",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-miniapp",
  //   name: "Miniapp banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/miniapp",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-profile",
  //   name: "Profile banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/profile",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-game-zone",
  //   name: "Game banner",
  //   icon: DownloadOutlined,
  //   route: "/game-zone-banner/list",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "tracking-pixel-banners",
  //   name: "Tracking Pixel Banners",
  //   icon: DownloadOutlined,
  //   route: "/tracking-pixel-banners/list",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "logos",
  //   name: "Homepage logos",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/card-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/insurance-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/securities-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "mini-app",
  //   name: "Mini App",
  //   icon: DownloadOutlined,
  //   route: "/linked-app-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "config-theme",
  //   name: "ConfigTheme",
  //   icon: DownloadOutlined,
  //   route: "/config-theme/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "delete-loan",
  //   name: "Delete loan",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP],
  // },
  // {
  //   id: "delete-lead-submitted",
  //   name: "Lead submitted",
  //   icon: DownloadOutlined,
  //   route: "/test-lead/list",
  //   menuParentId: "delete-loan",
  //   role: [ROLE.Admin, ROLE.OP],
  // },
  // {
  //   id: "delete-loan-refill",
  //   name: "Loan refill",
  //   icon: DownloadOutlined,
  //   route: "/test-loan-refill/list",
  //   menuParentId: "delete-loan",
  //   role: [ROLE.Admin, ROLE.OP],
  // },
  // {
  //   id: "income-report",
  //   name: "Hồ sơ thu nhập",
  //   icon: DownloadOutlined,
  //   route: "/income-report",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "accountant",
  //   name: "Kế toán",
  //   icon: DownloadOutlined,
  //   route: "/accountant-report",
  //   role: [ROLE.Admin, ROLE.Accountant],
  // },
  // {
  //   id: "product-limit",
  //   name: "Product limit",
  //   icon: DownloadOutlined,
  //   route: "/product-limits/list",
  //   role: [ROLE.Admin, ROLE.Setup],
  // },
  // {
  //   id: "abtesting-phase2",
  //   name: "ABTesting",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "flows",
  //   name: "Services",
  //   icon: DownloadOutlined,
  //   route: "/flows/list",
  //   menuParentId: "abtesting-phase2",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "flow-group",
  //   name: "User Flow Group",
  //   icon: DownloadOutlined,
  //   route: "/user-flow-group/list",
  //   menuParentId: "abtesting-phase2",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "greetings",
  //   name: "Greetings",
  //   icon: DownloadOutlined,
  //   route: "/greetings",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "oa-log",
  //   name: "OA log",
  //   icon: DownloadOutlined,
  //   route: "/oa/log",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "configs",
  //   name: "Hard Code",
  //   icon: DownloadOutlined,
  //   route: "/configs",
  //   menuParentId: "delete-loan",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "feature-configs",
  //   name: "Feature Configs",
  //   icon: DownloadOutlined,
  //   route: "/config-feature/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin],
  // },
  {
    id: 'category',
    name: 'Categories',
    icon: DownloadOutlined,
    route: '/category/list',
    menuParentId: 'article-parent',
    role: [ROLE.Admin, ROLE.OP],
  },
  // {
  //   id: "hold-lead",
  //   name: "Hold lead",
  //   icon: DownloadOutlined,
  //   route: "/hold-lead-logs/list",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin],
  // },
];

export const websiteMenus = [
  // {
  //   id: "bank",
  //   name: "Ngân hàng",
  //   icon: DownloadOutlined,
  //   route: "/banks/list",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "partner",
  //   name: "Đối tác",
  //   icon: DownloadOutlined,
  //   route: "/partners/list",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "campaign",
  //   name: "Chiến dịch",
  //   icon: DownloadOutlined,
  //   route: "/campaigns/list",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: 'product',
  //   name: 'Products',
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: 'product-card',
  //   name: 'Card',
  //   icon: DownloadOutlined,
  //   route: '/problem/list',
  //   menuParentId: 'product',
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: 'product-loan',
  //   name: 'Loan',
  //   icon: DownloadOutlined,
  //   route: '/loans/list',
  //   menuParentId: 'product',
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "product-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/insurances/list",
  //   menuParentId: "product",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "product-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/securities",
  //   menuParentId: "product",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-product",
  //   name: "Active Products",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/active-products-cards/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/active-products-loans/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/active-products-insurances/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "active-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/active-products-securities/list",
  //   menuParentId: "active-product",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "official-account",
  //   name: "Official Accounts",
  //   icon: DownloadOutlined,
  //   route: "/official-accounts/list",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead",
  //   name: "Lead",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/leads/card/new",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/leads/list",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  // {
  //   id: "lead-verify",
  //   name: "Verify Lead",
  //   icon: DownloadOutlined,
  //   route: "/filter/leads",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.Collaborator, ROLE.CustomSetup],
  // },
  {
    id: 'web-article-parent',
    name: 'Bài toán',
    icon: DownloadOutlined,
    role: [ROLE.Admin, ROLE.Guest],
  },
  // {
  //   id: 'web-category',
  //   name: 'Categories',
  //   icon: DownloadOutlined,
  //   route: '/web-category/list',
  //   menuParentId: 'web-article-parent',
  //   role: [ROLE.Admin, ROLE.Guest],
  // },
  {
    id: 'web-article',
    name: 'Xem danh sách',
    icon: DownloadOutlined,
    route: '/problems/list',
    menuParentId: 'web-article-parent',
    role: [ROLE.Admin, ROLE.Guest],
  },
  // {
  //   id: "report",
  //   name: "Report",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/report/cards",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/report/loans",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/report/insurances",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-loan-refill",
  //   name: "Loan Refill",
  //   icon: DownloadOutlined,
  //   route: "/report/loan-refill",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-feedback",
  //   name: "Feedback",
  //   icon: DownloadOutlined,
  //   route: "/report/feedback",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-ec-lead-status",
  //   name: "EC Lead Status",
  //   icon: DownloadOutlined,
  //   route: "/report/upload-ec-status",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "report-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/report/securities",
  //   menuParentId: "report",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.KeyAccountManager, ROLE.CustomSetup],
  // },
  // {
  //   id: "message",
  //   name: "Tin nhắn",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-list",
  //   name: "Tin nhắn",
  //   icon: DownloadOutlined,
  //   route: "/messages/list",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-create",
  //   name: "Soạn tin nhắn",
  //   icon: DownloadOutlined,
  //   route: "/messages/new",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-send",
  //   name: "Gửi tin nhắn",
  //   icon: DownloadOutlined,
  //   route: "/messages/send",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "message-history",
  //   name: "Lịch sử",
  //   icon: DownloadOutlined,
  //   route: "/message-tracks-details-summary/list",
  //   menuParentId: "message",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "broadcast",
  //   name: "Broadcast",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "broadcast-list",
  //   name: "Broadcast",
  //   icon: DownloadOutlined,
  //   route: "/broadcast/list",
  //   menuParentId: "broadcast",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "broadcast-create",
  //   name: "Tạo broadcast",
  //   icon: DownloadOutlined,
  //   route: "/broadcast/new",
  //   menuParentId: "broadcast",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "comment-approval",
  //   name: "Duyệt bình luận",
  //   icon: DownloadOutlined,
  //   route: "/review/list",
  //   role: [ROLE.Admin, ROLE.OP, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner",
  //   name: "Banner",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-visible",
  //   name: "Banner visible",
  //   icon: DownloadOutlined,
  //   route: "/banner/visible",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-welcome",
  //   name: "Welcome banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/welcome",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-featured",
  //   name: "Featured banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/featured",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-masthead",
  //   name: "Masthead banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/masthead",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-loanform",
  //   name: "Loanform banner step 1",
  //   icon: DownloadOutlined,
  //   route: "/banner/loanform",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-miniapp",
  //   name: "Miniapp banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/miniapp",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-profile",
  //   name: "Profile banner",
  //   icon: DownloadOutlined,
  //   route: "/banner/profile",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "banner-game-zone",
  //   name: "Game banner",
  //   icon: DownloadOutlined,
  //   route: "/game-zone-banner/list",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "tracking-pixel-banners",
  //   name: "Tracking Pixel Banners",
  //   icon: DownloadOutlined,
  //   route: "/tracking-pixel-banners/list",
  //   menuParentId: "banner",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "logos",
  //   name: "Homepage logos",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-card",
  //   name: "Card",
  //   icon: DownloadOutlined,
  //   route: "/card-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-loan",
  //   name: "Loan",
  //   icon: DownloadOutlined,
  //   route: "/partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-insurance",
  //   name: "Insurance",
  //   icon: DownloadOutlined,
  //   route: "/insurance-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "logo-securities",
  //   name: "Securities",
  //   icon: DownloadOutlined,
  //   route: "/securities-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "mini-app",
  //   name: "Mini App",
  //   icon: DownloadOutlined,
  //   route: "/linked-app-partner-logos/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "config-theme",
  //   name: "ConfigTheme",
  //   icon: DownloadOutlined,
  //   route: "/config-theme/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin, ROLE.Registered, ROLE.OP, ROLE.Setup, ROLE.CustomSetup],
  // },
  // {
  //   id: "delete-loan",
  //   name: "Delete loan",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin, ROLE.OP],
  // },
  // {
  //   id: "delete-lead-submitted",
  //   name: "Lead submitted",
  //   icon: DownloadOutlined,
  //   route: "/test-lead/list",
  //   menuParentId: "delete-loan",
  //   role: [ROLE.Admin, ROLE.OP],
  // },
  // {
  //   id: "delete-loan-refill",
  //   name: "Loan refill",
  //   icon: DownloadOutlined,
  //   route: "/test-loan-refill/list",
  //   menuParentId: "delete-loan",
  //   role: [ROLE.Admin, ROLE.OP],
  // },
  // {
  //   id: "income-report",
  //   name: "Hồ sơ thu nhập",
  //   icon: DownloadOutlined,
  //   route: "/income-report",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "accountant",
  //   name: "Kế toán",
  //   icon: DownloadOutlined,
  //   route: "/accountant-report",
  //   role: [ROLE.Admin, ROLE.Accountant],
  // },
  // {
  //   id: "product-limit",
  //   name: "Product limit",
  //   icon: DownloadOutlined,
  //   route: "/product-limits/list",
  //   role: [ROLE.Admin, ROLE.Setup],
  // },
  // {
  //   id: "abtesting-phase2",
  //   name: "ABTesting",
  //   icon: DownloadOutlined,
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "flows",
  //   name: "Services",
  //   icon: DownloadOutlined,
  //   route: "/flows/list",
  //   menuParentId: "abtesting-phase2",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "flow-group",
  //   name: "User Flow Group",
  //   icon: DownloadOutlined,
  //   route: "/user-flow-group/list",
  //   menuParentId: "abtesting-phase2",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "greetings",
  //   name: "Greetings",
  //   icon: DownloadOutlined,
  //   route: "/greetings",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "oa-log",
  //   name: "OA log",
  //   icon: DownloadOutlined,
  //   route: "/oa/log",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "configs",
  //   name: "Hard Code",
  //   icon: DownloadOutlined,
  //   route: "/configs",
  //   menuParentId: "delete-loan",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "feature-configs",
  //   name: "Feature Configs",
  //   icon: DownloadOutlined,
  //   route: "/config-feature/list",
  //   menuParentId: "logos",
  //   role: [ROLE.Admin],
  // },
  // {
  //   id: "hold-lead",
  //   name: "Hold lead",
  //   icon: DownloadOutlined,
  //   route: "/hold-lead-logs/list",
  //   menuParentId: "lead",
  //   role: [ROLE.Admin],
  // },
];
